import { Routes } from '@angular/router';
import { LoginComponent } from './components/login/login.component';
import { HomeComponent } from './components/home/home.component';
import { ContactoComponent } from './components/contacto/contacto.component';
import { RegistroComponent } from './components/registro/registro.component';
import { MetodoPagoComponent } from './components/metodo-pago/metodo-pago.component';
import { PerfilComponent } from './components/perfil/perfil.component';
import { PromocionesComponent } from './components/promociones/promociones.component';
import { DetalleCarroComponent } from './components/detalle-carro/detalle-carro.component';
import { CarritoComponent } from './components/carrito/carrito.component';
import { LiteraturaComponent } from './components/categorias/literatura/literatura.component';
import { NovelasComponent } from './components/categorias/novelas/novelas.component';
import { ComicsMangasComponent } from './components/categorias/comics-mangas/comics-mangas.component';
import { InformaticaComponent } from './components/categorias/informatica/informatica.component';
import { AutoAyudaComponent } from './components/categorias/auto-ayuda/auto-ayuda.component';
import { GestionUsuariosComponent } from './components/administracion/gestion-usuarios/gestion-usuarios.component';
import { GestionProductosComponent } from './components/administracion/gestion-productos/gestion-productos.component';
import { AdminHomeComponent } from './components/administracion/admin-home/admin-home.component';
import { RecuperacionComponent } from './components/recuperacion/recuperacion.component';
import { RestablecerContrasenaComponent } from './components/restablecer-contrasena/restablecer-contrasena.component';
import { PagoExitosoComponent } from './components/pago-exitoso/pago-exitoso.component';

export const routes: Routes = [
    { path: 'pago-exitoso', component: PagoExitosoComponent },
    { path: 'admin-home', component: AdminHomeComponent },
    { path: 'gestion-usuarios', component: GestionUsuariosComponent },
    { path: 'gestion-productos', component: GestionProductosComponent },
    { path: 'literatura', component: LiteraturaComponent },
    { path: 'novelas', component: NovelasComponent },
    { path: 'comics-mangas', component: ComicsMangasComponent },
    { path: 'informatica', component: InformaticaComponent },
    { path: 'auto-ayuda', component: AutoAyudaComponent },
    { path: 'restablecer-contrasena', component: RestablecerContrasenaComponent },
    { path: 'recuperacion', component: RecuperacionComponent },
    { path: 'contacto', component: ContactoComponent },
    { path: 'carrito', component: CarritoComponent },
    { path: 'metodo-pago', component: MetodoPagoComponent },
    { path: 'producto/:id', component: DetalleCarroComponent },
    { path: 'perfil', component: PerfilComponent },
    { path: 'promociones', component: PromocionesComponent },
    { path: 'registro', component: RegistroComponent },
    { path: 'home', component: HomeComponent },
    { path: 'login', component: LoginComponent },
    { path: '**', redirectTo: 'home' }
];
